server:
  port: 8082
spring:
  application:
    name: "transaction-service"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/transaction-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: ${spring.application.name}-producer
      acks: all
      retries: 5

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        spring.json.add.type.headers: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          user-account-service:
            connect-timeout: 3000
            read-timeout: 6000
            logger-level: basic

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    configs:
      default:
        timeoutDuration: 8s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    shutdown:
      enabled: false
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "transaction-service"
    version: "1.0.0"

logging:
  level:
    com:
      transaction_service: DEBUG

app:
  kafka:
    topics:
      balance-update-requested: balance-update-events
      balance-update-notification: balance-update-notification-events
      transaction-completed: banking.transaction.completed.v1
      transaction-failed: transaction-failed-events

      transfer-debit-requested: transfer-debit-requested.v1
      transfer-debit-reserved: transfer-debit-reserved.v1
      transfer-debit-failed: transfer-debit-failed.v1
      transfer-credit-requested: transfer-credit-requested.v1
      transfer-credit-completed: transfer-credit-completed.v1
      transfer-credit-failed: transfer-credit-failed.v1
      transfer-refund-requested: transfer-refund-requested.v1
      transfer-compensated: transfer-compensated.v1

