server:
  port: 8082
spring:
  application:
    name: "transaction-service"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/transaction-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          user-account-service:
            connect-timeout: 3000
            read-timeout: 6000
            logger-level: basic

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    configs:
      default:
        timeoutDuration: 8s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    shutdown:
      enabled: false
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "transaction-service"
    version: "1.0.0"

logging:
  level:
    com:
      transaction_service: DEBUG