server:
  port: 8081
spring:
  application:
    name: "user-account-service"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/users-account-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      client-id: ${spring.application.name}-producer
      acks: all
      retries: 5

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        spring.json.add.type.headers: true

    consumer:
      group-id: account-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          json.type.mapping: com.transaction_service.kafka.dto.BalanceUpdateEvent:com.user_account_service_service.kafka.dto.BalanceUpdateEvent

#jwt config
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    shutdown:
      enabled: false
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "user-account-service"
    version: "1.0.0"

logger:
  level:
    com:
      user-account-service: DEBUG

app:
  kafka:
    topics:
      user-registered: banking.user.registered.v1
      balance-update-notification: balance-update-notification-events

      transfer-debit-requested: transfer.debit.requested.v1
      transfer-debit-reserved: transfer.debit.reserved.v1
      transfer-debit-failed: transfer.debit.failed.v1

      transfer-credit-requested: transfer.credit.requested.v1
      transfer-credit-completed: transfer.credit.completed.v1
      transfer-credit-failed: transfer.credit.failed.v1

      transfer-refund-requested: transfer.refund.requested.v1
      transfer-compensated: transfer.compensated.v1
