apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
type: Opaque
stringData:
  DB_USERNAME: "replace-me"
  DB_PASSWORD: "replace-me"
  JWT_SECRET: "replace-me"
  JWT_EXPIRATION: "86400000"
  SPRING_MAIL_USERNAME: "replace-me"
  SPRING_MAIL_PASSWORD: "replace-me"
